#!/bin/bash

# Set repository variables
owner="piyoshkr"
repository="script-repo"

# Set API URL to get latest release
api_url="https://api.github.com/repos/$owner/$repository/releases/latest"

# Get the latest release information
release_info=$(curl -s "$api_url")
latest_version=$(echo "$release_info" | grep -oP '"tag_name": "\K(.*)(?=")')

# Set directory path for the repository
repository_path="$HOME/$repository"

# Check if the repository directory already exists
if [ -d "$repository_path" ]; then
    echo "Repository already exists."
    cd "$repository_path"
    current_version=$(git describe --abbrev=0 --tags)
else
    # Clone the repository
    echo "Cloning repository..."
    git clone "https://github.com/$owner/$repository.git" "$repository_path"
    echo "Repository cloned."
    cd "$repository_path"
fi

# Check if the script version is up to date
if [ "$latest_version" != "$(git describe --abbrev=0 --tags)" ]; then
    echo "A new version of the script is available."
fi
                                                                                                     
